- name: Update all packages
  yum:
    name: "*"
    state: latest

- name: Install Docker
  yum:
    name: docker
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Install Grafana Loki Docker plugin
  command: >
    docker plugin install grafana/loki-docker-driver:3.3.2-amd64
    --alias loki --grant-all-permissions
  args:
    creates: /var/lib/docker/plugins/grafana_loki-docker-driver

- name: Configure Docker daemon with metrics and Loki logging
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "debug": true,
        "metrics-addr": "0.0.0.0:9323",
        "experimental": true,
        "log-driver": "loki",
        "log-opts": {
          "mode": "non-blocking",
          "loki-url": "http://127.0.0.1:3100/loki/api/v1/push",
          "loki-batch-size": "400",
          "loki-retries": "2",
          "max-size": "10m",
          "max-file": "3"
        }
      }
  notify: Restart Docker